name: Deploy backend

on:
    push:
        branches:
            - main
        paths:
            - "packages/backend/**"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build backend
              run: yarn backend:build

            - name: Tar build files
              run: |
                  packages/backend
                  tar -czf backend.tar.gz dist package.json

            - name: Copy to server
              uses: pierrickdelrieu/scp-action@0.1.2
              with:
                  host: ${{ secrets.DROPLET_HOST }}
                  ssh_username: ${{ secrets.DROPLET_USER }}
                  ssh_key: ${{ secrets.DROPLET_KEY }}
                  source_dir: packages/backend/backend.tar.gz
                  destination_dir: /tmp/backend.tar.gz
                  rm: true

            - name: Extract and restart server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.DROPLET_HOST }}
                  username: ${{ secrets.DROPLET_USER }}
                  key: ${{ secrets.DROPLET_KEY }}
                  script: |
                      pm2 stop backend

                      mkdir -p /var/www/backend
                      tar -xzf /tmp/backend.tar.gz /var/www/backend
                      rm /tmp/backend.tar.gz

                      pm2 start backend
                      pm2 save
